### ISSUE TITLE
xcode7.0.1简历新的工程出现链接错误

### ISSUE THREAD

**Issue by JRJian** [leancloud/LeanStorageDemo-iOS#10]
xcode7.0.1新建个project
使用cocoa pods依赖管理AVOSCloud，安装成功后
在appdelegate didFinishLaunchingWithOptions 调用
[AVOSCloud setApplicationId:AVOSCloudAppID
                      clientKey:AVOSCloudAppKey];
编译报错提示链接的x86_64静态库构建版本不存在

**Comment by lzwjava** [comment]
修好了？

**Comment by JRJian** [comment]
嗯。我重新建立了个demo，pod一下就好了，也不知道为啥。
