### ISSUE TITLE
xcode 升级后 swift 2.0 demo无法编译

### ISSUE THREAD

**Issue by x1911** [leancloud/LeanStorageDemo-iOS#9]
'stringByAppendingPathComponent' is unavailable: Use URLByAppendingPathComponent on NSURL instead.

如题，pod install 更新后仍然出现5个错误，swift版本无法通过编译

**Comment by lzwjava** [comment]
https://github.com/leancloud/LeanStorageDemo-iOS/commit/1f793bb3d4126940ff2c6d971e8a2b7b4a98658a

Fixed, Thanks
